# Generated by Django 5.2.8 on 2025-11-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('viewers', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('food', 'Oziq-ovqat'), ('drinks', 'Ichimliklar'), ('clothes', 'Kiyim-kechak'), ('electronics', 'Elektronika'), ('appliances', 'Maishiy texnika'), ('accessories', 'Aksessuarlar'), ('kids', 'Bolalar uchun mahsulotlar')])),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
